CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!bst kenji'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!moves koffing'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!types gengar'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!getgen'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!bst nidoking'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!setgen sword'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!types clefable'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!setgen firered'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!types clefable'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!moves koffing'