CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!bst kenji'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!bst celebi'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!moves koffing'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!types gengar'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!getgen'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!bst nidoking'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!setgen sword'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!types clefable'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!setgen firered'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!types clefable'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!moves koffing'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!types magnemite'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!types magnemite +blue'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!attack fire grass'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!attack ice dragon/flying'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!attack fighting ghost/dark'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!attack bug water'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!attack fire rock/normal'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '!terry'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '@bigstevebot info'
CLI_USER="tester" CLI_CHANNEL="#tester" npm test '@bigstevebot credits'