name: Deploy to Prod

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup ssh agent for deployment
      - uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.LIVE_SERVER_PRIVATE_KEY }}

      - name: Setup config and run shipit
        run: |
          npm install
          mkdir config
          echo '{"deploy_user":"${{secrets.LIVE_SERVER_USER}}","deploy_server":"${{secrets.LIVE_SERVER_IP}}","deploy_dir":"/home/centos/prod","repo_url":"git@github.com:sjb9774/nubot.git"}' > config/local.json
          npx shipit production
